[package]
name = "game_of_life"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch = "0.3.1"
# where we are going, we dont need dependencies
